[package]
authors = ["Jorge Aparicio <japaricious@gmail.com>", "Brook Heisler <brookheisler@gmail.com>"]
name = "criterion"
version = "0.2.1"

description = "Statistics-driven micro-benchmarking library"
homepage = "https://japaric.github.io/criterion.rs/book/index.html"
repository = "https://github.com/japaric/criterion.rs"
readme = "README.md"
keywords = ["criterion", "benchmark"]
categories = ["development-tools::profiling"]
license = "Apache-2.0/MIT"

[dependencies]

[dev-dependencies]

[badges]
travis-ci = { repository = "japaric/criterion.rs" }
appveyor = { repository = "japaric/criterion.rs", id = "4255ads9ctpupcl2" }
coveralls = { repository = "japaric/criterion.rs" }
maintenance = { status = "actively-developed" }

[features]
real_blackbox = []
default = []

[workspace]

[[bench]]
name = "bench_main"
harness = false

[lib]
bench = false
